pr: none
trigger: none

pool:
  name: Default

variables:
  VM_HOST: $(DEX_VM_HOST) # Update with your VM's host
  VM_USER: $(DEX_VM_USER) # Update with your VM's username
  PROJECT_PATH: $(PROJECT_RELATIVE_PATH) # Relative path to project directory
  SSH_PUBLIC_KEY: $(DEX_SSH_VM_PUBLIC_KEY)

jobs:
  - job: QodanaScan
    displayName: "Qodana Scan"
    steps:
      - task: QodanaScan@2024
        env:
          QODANA_TOKEN: $(QODANA_TOKEN)
