pr: none
trigger: none

pool:
  name: Default

variables:
  sourceRepo: $(SOURCE_REPO)
  sourceBranch: "main"
  azureSourcePat: $(AZURE_SOURCE_PAT)
  azureDevOpsUser: $(AZURE_GIT_USER)
  azureRepo: $(APP_SERVICE_REPO)
  azureBranch: "master"

stages:
  - stage: TestCode
    jobs:
      - job: TestBuildingCodeRepo
        steps:
          - checkout: self
            displayName: "Checkout source code"

          - script: |
              npm install
              npm run build
            displayName: "Building project for testing"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/.next'
              artifact: 'build'
            displayName: "Publish build artifacts"

  - stage: PushToAzure
    dependsOn: TestCode
    jobs:
      - job: PushAzure
        steps:
          - download: current
            artifact: build
            displayName: "Download build artifacts"

          - script: |
              git clone https://$(azureDevOpsUser)@$(azureRepo) source
              cd source
              git remote add azure https://$(azureDevOpsUser)@$(azureRepo)  # Add 'azure' as the remote
              git checkout -b $(azureBranch)
              rsync -av --exclude='.git' --exclude='.git/' $(Pipeline.Workspace)/build/ .  # Exclude .git directory
              git config user.email "devs@dexfreight.io"
              git config user.name "devs@dexfreight.io"
              git add .
              git commit -m "Automated commit: Update from build" || echo "No changes to commit"
              git push azure $(azureBranch)
            displayName: "Clone source repo and push changes to Azure repository"
