pr: none
trigger: none

pool:
  name: Default

variables:
  VM_HOST: $(DEX_VM_HOST)          # Update with your VM's host
  VM_USER: $(DEX_VM_USER)      # Update with your VM's username
  PROJECT_PATH: $(PROJECT_RELATIVE_PATH) # Relative path to project directory
  SSH_PUBLIC_KEY: $(DEX_SSH_VM_PUBLIC_KEY)

jobs:
- job: QodanaScan
  displayName: 'Qodana Scan'
  steps:
  - task: QodanaScan@2024
    inputs:
      token: $(QODANA_TOKEN)
- job: DeployChangesAndCompose
  displayName: 'Deploy Changes and Updating Website in VM'
  steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: |
        |1|XoIxBoyHXXyt5EWpJS9fQroDF00=|0ZsfkUI7/5xc2f7KXB6ojJM+xw0= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEurS/eOwNVafquXm9u0MeCohCqxg6zN7cMOEymCtvoc
        |1|+d+8LqEW0wF7Uahh8AwnTz60zb0=|iNBXN2lAxErHnh95QhYFMxPPcF0= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
      sshPublicKey: '$(SSH_PUBLIC_KEY)'
      sshKeySecureFile: 'HKI-website_key.pem'

  - script: |
      ssh -o StrictHostKeyChecking=no $(VM_USER)@$(VM_HOST) << 'EOF'
      cd /home/$(VM_USER)/$(PROJECT_PATH) # Update with the correct path on your VM
      git pull origin main # Pull the latest changes from the repo
      sudo docker compose up -d --build
      EOF
    displayName: 'Building Docker Image'
