pr: none
trigger: none

pool:
  name: Default

variables:
  sourceRepo: $(SOURCE_REPO)
  sourceBranch: "main"
  azureRepo: $(APP_SERVICE_REPO)
  azureBranch: "master"

stages:
  - stage: TestCode
    jobs:
      - job: TestBuildingCodeRepo
        steps:
          - checkout: self
          - script: |
              npm install
              npm run build
            displayName: "Building project for testing"

          - task: PublishBuildArtifacts@1
            inputs:  
              PathtoPublish: $(Build.SourcesDirectory)/.next
              artifact: 'build'
              publishLocation: 'Pipeline'
            displayName: "Publish build artifacts"

  - stage: PushToAzure
    dependsOn: TestCode
    jobs:
      - job: PushAzure
        steps:
          - download: current
            artifact: build
            displayName: "Download build artifacts"
          - script: |
              git clone $(sourceRepo) source
              cd source
              git checkout $(sourceBranch)
              rsync -av --exclude='.git' $(Pipeline.Workspace)/build/ .
              git config user.email "you@example.com"
              git config user.name "Your Name"
              git add .
              git commit -m "Automated commit: Update from build"
              git branch -M $(azureBranch)
              git remote add azure $(azureRepo)
              git push azure $(azureBranch)
            displayName: "Clone source repo and push changes to Azure repository"
