pr: none
trigger: none

pool:
  name: Default

variables:
  sourceRepo: $(SOURCE_REPO)
  sourceBranch: "main"
  azureRepo:  $(APP_SERVICE_REPO)
  azureBranch: "master"

stages:
  - stage: TestCode
    jobs:
      - job: TestBuildingCodeRepo
        steps:
          - checkout: none
          - script: |
              npm run build
            displayName: "Building project for testing"

  - stage: PushToAzure
    dependsOn: TestCode
    jobs:
      - job: PushAzure
        steps:
          - checkout: none
          - script: |
              git clone $(sourceRepo) temp
              cd temp
              git checkout $(sourceBranch)
            displayName: "Clone source repository"

          - script: |
              cd temp
              git push $(azureRepo) $(azureBranch)
            displayName: "Push changes to Azure repository"
