pr: none
trigger: none

pool:
  name: Book

variables:
  image_name: 'hpi-front-next'
  image_tag: 'latest'

steps:
# Checkout code from the Azure Repo
- checkout: self
  displayName: 'Checkout Code'

- task: DownloadSecureFile@1
  displayName: 'Download Publish Profile'
  name: appProfile
  inputs:
    secureFile: 'AppServiceProfile.PublishSettings'

- script: |
    docker compose -f docker-compose.yml build
  displayName: 'Build Docker Image'

- script: |
    docker tag $(image_name):$(image_tag) $(image_name):$(Build.BuildId)
  displayName: 'Tag Docker Image'

- script: |
    docker save $(image_name):$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)/$(image_name).tar
  displayName: 'Save Docker Image to Tar File'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(image_name).tar'
    ArtifactName: 'docker-image'
  displayName: 'Publish Docker Image as an Artifact'

- task: AzureRmWebAppDeployment@4
  inputs:
    appType: 'webAppContainer'
    WebAppName: '$(image_name)'
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(appProfile.secureFilePath)'
    PublishProfilePassword: '$(publishProfilePWD)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(image_name).tar'
    DockerImageTag: 'latest'
  displayName: 'Deploy Docker Image to Azure Web App'