pr: none
trigger: none

pool:
  name: Default

variables:
  image_name: 'hpi-front-next'
  image_tag: 'latest'

steps:
# Checkout code from the Azure Repo
- checkout: self
  displayName: 'Checkout Code'

- script: |
    docker-compose -f docker-compose.yml build
  displayName: 'Build Docker Image'

- script: |
    docker tag $(image_name):$(image_tag) $(image_name):$(Build.BuildId)
  displayName: 'Tag Docker Image'

- script: |
    docker save $(image_name):$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)/$(image_name).tar
  displayName: 'Save Docker Image to Tar File'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(image_name).tar'
    ArtifactName: 'docker-image'
  displayName: 'Publish Docker Image as an Artifact'

- task: AzureRmWebAppDeployment@4
  inputs:
    WebAppName: '$(image_name)'
    ConnectionType: 'PublishProfile'
    PublishProfilePath: AppServiceProfile.PublishSettings
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(image_name).tar'
  displayName: 'Deploy Docker Image to Azure Web App'