pr: none
trigger: none

pool:
  name: Default

variables:
  sourceRepo: $(SOURCE_REPO)
  sourceBranch: "main"
  azureSourcePat: $(AZURE_SOURCE_PAT)
  azureDevOpsUser: $(AZURE_GIT_USER)
  azureDevOpsPass: $(AZURE_GIT_PASS)
  azureRepo: $(APP_SERVICE_REPO)
  azureBranch: "master"

stages:
  - stage: TestCode
    jobs:
      - job: TestBuildingCodeRepo
        steps:
          - checkout: self
            displayName: "Checkout source code"

          - script: |
              npm install
              npm run build
            displayName: "Building project for testing"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'build'
            displayName: "Publish build artifacts"

  - stage: PushToAzure
    dependsOn: TestCode
    jobs:
      - job: PushAzure
        steps:
          - download: current
            artifact: build
            displayName: "Download build artifacts"

           - script: |
              echo "Pipeline Workspace: $(Pipeline.Workspace)"
              ls -la $(Pipeline.Workspace)
            displayName: "Echo Pipeline.Workspace and List Contents"
