version: "3"
services:     
  next:
    container_name: next
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - dev

 
  nginx:
    container_name: nginx
    image: nginx
    working_dir: /www
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

networks:
    dev:
      driver: bridge